apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.tech.dnb.no/dnb/dob/playground/$CI_PROJECT_NAME.git
    targetRevision: main
    path: crossplane
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true