apiVersion: ecs.aws.upbound.io/v1beta1
kind: Service
metadata:
  name: hello-world-api
  annotations:
    meta.upbound.io/example-id: ecs/v1beta1/service
    upjet.upbound.io/manual-intervention: "Resourrce stuck in update loop"
spec:
  forProvider:
    taskDefinitionSelector:
      matchLabels:
          testing.upbound.io/example-name: hello-world-api
    clusterSelector:
      matchLabels:
          testing.upbound.io/example-name: hello-world-api
    region: eu-west-1
    launchType: FARGATE
    propagateTags: TASK_DEFINITION